---
dist: xenial
language: ruby
rvm:
- 2.5.5
cache:
  bundler: true
addons:
  postgresql: '10'
  apt:
    packages:
    - libarchive-dev
script: bundle exec manageiq-cross_repo
matrix:
  fast_finish: true
env:
  global:
  - REPOS=GrumpyTech/manageiq-ui-classic#1
  matrix:
  - TEST_REPO=GrumpyTech/manageiq
